### ISSUE TITLE
Fix widescreen coding issues (my issues)

### ISSUE THREAD

**Issue by Gaxeer** [ss220club/WyccerraBay220#28]
### Description of issue

Fix widescreen coding issues (my issues)

### Steps to reproduce

Not a bug

### Client version, server revision, & game ID

BYOND 515

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Aks11-11** [comment]
To address widescreen coding issues, here are some steps you can take:

Identify the Specific Issues: Pinpoint exactly what aspects of the game are affected by widescreen display. Are UI elements misaligned or stretched? Is the gameplay area not scaling correctly?
Adjust UI Scaling: Ensure that your UI elements are set up to scale appropriately based on the screen resolution. You may need to use relative positioning and sizing rather than absolute values.
Aspect Ratio Handling: Make sure your game's rendering system accounts for different aspect ratios. This might involve adjusting how backgrounds or game elements are drawn to fit various screen sizes while maintaining the correct proportions.
Testing: Test your game on various widescreen resolutions to see how it behaves. Pay attention to both common widescreen aspect ratios like 16:9 as well as less common ones.
BYOND Specifics: Utilize BYOND's documentation and community resources to address any specific quirks or features related to widescreen support in BYOND 515.

**Comment by Gaxeer** [comment]
Вроде бы исправлено
